openapi: 3.1.0
info:
  title: Archivage
  description: API pour l'archivage des pièces justificatives et documents CEE
  version: 1.0.0
tags:
  - name: Archive
paths:
  /archives:
    get:
      summary: Recherche une liste d'archives
      operationId: getArchivesBy
      tags:
        - Archive
      parameters:
        - name: itemsPerPage
          in: query
          schema:
            type: integer
            minimum: 10
            maximum: 100
            default: 25
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: metadata
          in: query
          description: Liste des métadonnées
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: Liste des archives trouvées
          headers:
            X-Pagination-TotalItems:
              description: Nombre total d'éléments retournés
              schema:
                type: integer
                minimum: 0
            X-Pagination-Page-Last:
              description: Dernière page
              schema:
                type: string
                format: url
            X-Pagination-Page-Current:
              description: Page courante
              schema:
                type: string
                format: url
            X-Pagination-Page-Next:
              description: Page suivante
              schema:
                type: string
                format: url
          content:
            application/json:
              schema:
                type: array
                items: &a1
                  title: Archive
                  type: object
                  properties:
                    uuid:
                      title: Identifiant unique d'archive
                      type: string
                      format: uuid
                    metadata:
                      title: Métadonnées
                      type: array
                      items:
                        title: Métadonnées
                        type: object
                        properties:
                          depot:
                            type: string
                            format: uuid
                          controle:
                            type: string
                            format: uuid
                          operation:
                            type: string
                            format: uuid
                          code:
                            type: string
                    url:
                      title: Lien permettant d'ouvrir le fichier
                      type: string
                  required:
                    - uuid
                    - metadata
                    - url
    post:
      summary: Création d'une archive
      opeartionId: createArchive
      tags:
        - Archive
      requestBody:
        content:
          multipart/form-data:
            schema: &a4
              title: Archive
              type: object
              properties:
                document:
                  type: string
                  format: binary
                metadata:
                  type: array
                  items:
                    type: object
                    properties:
                      depot:
                        type: string
                        format: uuid
                      controle:
                        type: string
                        format: uuid
                      operation:
                        type: string
                        format: uuid
                      code:
                        type: string
              required:
                - document
                - metadata
      responses:
        "201":
          description: Archive créée
          content:
            application/json:
              schema: *a1
        "422":
          description: Requête invalide
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                    const: 422
                  detail:
                    type: string
                  errors:
                    type: array
                    items:
                      title: Erreur
                      type: object
                      properties:
                        keyword:
                          type: string
                        propertyPath:
                          type: string
                        message:
                          type: string
        "503":
          description: Service temporairement indisponible
  /archives/{uuid}:
    get:
      summary: Recherche d'une archive par son identifiant
      operationId: getArchiveByUuid
      tags:
        - Archive
      parameters:
        - &a2
          name: uuid
          in: path
          description: UUID de l'archive
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Archive retournée
          content:
            application/json:
              schema: *a1
        "404": &a3
          description: Ressource non trouvée
    delete:
      summary: Supprimer une archive
      operationId: removeArchive
      tags:
        - Archive
      parameters:
        - *a2
      responses:
        "204":
          description: Requête exécutée avec succès sans retourner de contenu
        "404": *a3
  /archives/{uuid}/content:
    get:
      summary: Recherche le contenu d'une archive par son identifiant
      operationId: getArchiveContentByUuid
      tags:
        - Archive
      parameters:
        - *a2
      responses:
        "200":
          description: Archive retournée
          content:
            application/json:
              schema:
                oneOf:
                  - type: string
                    format: binary
                  - type: string
                    format: base64
        "404": *a3
components:
  parameters:
    uuid: *a2
  schemas:
    createArchive: *a4
    archive: *a1
