openapi: 3.1.0
info:
  title: Répertoire
  description: API d'accès au répertoire national des opérations standardisées
    d'économies d'énergie
  version: 1.0.0
tags:
  - name: Fiche
  - name: Bonification
paths:
  /fiches:
    get:
      summary: Recherche une liste des fiches d'opération standardisée par attributs
      operationId: getFichesBy
      tags:
        - Fiche
      parameters:
        - name: code
          in: query
          schema: &a17
            $schema: https://json-schema.org/draft/2020-12/schema
            title: Code
            type: string
            pattern: (AGRI|BAR|BAT|IND|RES|TRA)[-](BA|CH|EC|EN|EQ|SE|TH|UT)[-][0-9]*([-]SE)?
            examples:
              - AGRI-EQ-101
              - BAT-EN-101
              - BAR-EN-101
              - IND-BA-110
              - RES-CH-101
              - TRA-EQ-101
        - name: secteur
          in: query
          schema: &a15
            $schema: https://json-schema.org/draft/2020-12/schema
            title: Secteur d'application
            type: string
            oneOf:
              - &a1
                const: AGRI
                title: Agriculture
              - &a2
                const: BAR
                title: Bâtiment résidentiel
              - &a3
                const: BAT
                title: Bâtiment tertiaire
              - &a4
                const: IND
                title: Industrie
              - &a5
                const: RES
                title: Réseaux
              - &a6
                const: TRA
                title: Transport
            $defs:
              AGRI: *a1
              BAR: *a2
              BAT: *a3
              IND: *a4
              RES: *a5
              TRA: *a6
            examples:
              - AGRI
              - BAR
              - BAT
              - IND
              - RES
              - TRA
        - name: sousSecteur
          in: query
          schema: &a16
            $schema: https://json-schema.org/draft/2020-12/schema
            title: Sous-secteur d'application
            type: string
            oneOf:
              - &a7
                const: BA
                title: Bâtiments
              - &a8
                const: CH
                title: Chaleur et Froid
              - &a9
                const: EC
                title: Eclairage
              - &a10
                const: EN
                title: Enveloppe
              - &a11
                const: EQ
                title: Equipement
              - &a12
                const: SE
                title: Services
              - &a13
                const: TH
                title: Thermique
              - &a14
                const: UT
                title: Utilités
            $defs:
              BA: *a7
              CH: *a8
              EC: *a9
              EN: *a10
              EQ: *a11
              SE: *a12
              TH: *a13
              UT: *a14
            examples:
              - BA
              - CH
              - EC
              - EN
              - EQ
              - SE
              - TH
              - UT
        - name: date
          in: query
          description: Date prévue de l'opération
          schema:
            type: string
            format: date
        - name: metropole
          in: query
          description: Fiche applicable en France métropolitaine
          schema:
            type: boolean
        - name: outreMer
          in: query
          description: Fiche applicable en France d'outre-mer
          schema:
            type: boolean
      responses:
        "200":
          description: Fiches d'opération standardisée retournées
          content:
            application/json:
              schema:
                type: array
                items: &a19
                  type: object
                  properties:
                    id: &a18
                      title: Fiche d'opération standardisée
                      type: string
                      oneOf:
                        - const: BAR-EN-101v39-4
                        - const: BAR-EN-101v54-5
                        - const: BAR-EN-102v39-2
                        - const: BAR-EN-103v39-5
                        - const: BAR-EN-104v14-1
                        - const: BAR-EN-104v54-2
                        - const: BAR-EN-105v39-3
                        - const: BAR-EN-106v33-4
                        - const: BAR-EN-107v20-3
                        - const: BAR-EN-108v37-2
                        - const: BAR-EN-108v54-3
                        - const: BAR-EN-109v24-1
                        - const: BAR-EN-110v35-1
                        - const: BAR-EQ-110v15-1
                        - const: BAR-EQ-115v28-1
                        - const: BAR-SE-104v19-1
                        - const: BAR-SE-105v28-1
                        - const: BAR-SE-106v32-1
                        - const: BAR-SE-107v37-1
                        - const: BAR-SE-108v48-1
                        - const: BAR-SE-109v54-1
                        - const: BAR-TH-101v17-1
                        - const: BAR-TH-102v17-1
                        - const: BAR-TH-104v41-3
                        - const: BAR-TH-106v23-2
                        - const: BAR-TH-107-SEv14-1
                        - const: BAR-TH-107v14-1
                        - const: BAR-TH-110v16-1
                        - const: BAR-TH-111v17-1
                        - const: BAR-TH-112v46-3
                        - const: BAR-TH-113v41-3
                        - const: BAR-TH-116v17-1
                        - const: BAR-TH-117v14-1
                        - const: BAR-TH-118v14-1
                        - const: BAR-TH-122v15-1
                        - const: BAR-TH-123v17-1
                        - const: BAR-TH-123v54-2
                        - const: BAR-TH-124v35-3
                        - const: BAR-TH-125v40-4
                        - const: BAR-TH-125v54-5
                        - const: BAR-TH-127v40-4
                        - const: BAR-TH-127v54-5
                        - const: BAR-TH-129v27-3
                        - const: BAR-TH-130v26-1
                        - const: BAR-TH-130v54-2
                        - const: BAR-TH-135v35-2
                        - const: BAR-TH-137v45-3
                        - const: BAR-TH-139v23-2
                        - const: BAR-TH-141v15-1
                        - const: BAR-TH-143v25-1
                        - const: BAR-TH-143v51-5
                        - const: BAR-TH-145v36-3
                        - const: BAR-TH-145v52-4
                        - const: BAR-TH-148v15-2
                        - const: BAR-TH-150v14-1
                        - const: BAR-TH-155v40-4
                        - const: BAR-TH-158v35-2
                        - const: BAR-TH-159v44-3
                        - const: BAR-TH-159v50-4
                        - const: BAR-TH-160v39-2
                        - const: BAR-TH-160v50-3
                        - const: BAR-TH-160v54-4
                        - const: BAR-TH-161v28-1
                        - const: BAR-TH-161v54-2
                        - const: BAR-TH-162v28-1
                        - const: BAR-TH-163v38-2
                        - const: BAR-TH-164v36-2
                        - const: BAR-TH-164v52-3
                        - const: BAR-TH-165v34-1
                        - const: BAR-TH-166v38-1
                        - const: BAR-TH-167v38-1
                        - const: BAR-TH-168v40-1
                        - const: BAR-TH-169v46-1
                        - const: BAR-TH-170v54-1
                        - const: BAR-TH-171v55-1
                        - const: BAR-TH-172v55-1
                      $defs:
                        agri:
                          type: string
                          pattern: (AGRI)[-](BA|CH|EC|EN|EQ|SE|TH|UT)[-][0-9]+([-]SE)?v[0-9]+[-][0-9]+
                        bar:
                          type: string
                          pattern: (BAR)[-](BA|CH|EC|EN|EQ|SE|TH|UT)[-][0-9]+([-]SE)?v[0-9]+[-][0-9]+
                        bat:
                          type: string
                          pattern: (BAT)[-](BA|CH|EC|EN|EQ|SE|TH|UT)[-][0-9]+([-]SE)?v[0-9]+[-][0-9]+
                        ind:
                          type: string
                          pattern: (IND)[-](BA|CH|EC|EN|EQ|SE|TH|UT)[-][0-9]+([-]SE)?v[0-9]+[-][0-9]+
                        res:
                          type: string
                          pattern: (RES)[-](BA|CH|EC|EN|EQ|SE|TH|UT)[-][0-9]+([-]SE)?v[0-9]+[-][0-9]+
                        tra:
                          type: string
                          pattern: (TRA)[-](BA|CH|EC|EN|EQ|SE|TH|UT)[-][0-9]+([-]SE)?v[0-9]+[-][0-9]+
                    secteur:
                      title: Secteur d'application
                      type: object
                      properties:
                        code: *a15
                        nom:
                          title: Nom
                          type: string
                      required:
                        - code
                        - nom
                    sousSecteur:
                      title: Sous secteur d'application
                      type: object
                      properties:
                        code: *a16
                        nom:
                          title: Nom
                          type: string
                      required:
                        - code
                        - nom
                    code: *a17
                    version:
                      type: string
                      pattern: ^[0-9]+[.][0-9]+$
                      examples:
                        - "14.1"
                        - "33.4"
                    nom:
                      type: string
                    dateDebut:
                      type: string
                      format: date
                    dateFin:
                      type:
                        - string
                        - "null"
                      format: date
                    metropole:
                      type: boolean
                    outreMer:
                      type: boolean
                  required:
                    - id
                    - code
                    - secteur
                    - sousSecteur
                    - nom
                    - version
                    - dateDebut
                    - dateFin
                    - metropole
                    - outreMer
  /fiches/{id}:
    get:
      summary: Recherche une fiche d'opération standardisée par son identifiant unique
      operationId: getFicheById
      tags:
        - Fiche
      parameters:
        - name: id
          in: path
          schema: *a18
      responses:
        "200":
          description: Fiche d'opération standardisée retournée
          content:
            application/json:
              schema: *a19
        "404":
          description: Fiche d'opération standardisée non trouvée
  /bonifications:
    get:
      summary: Recherche une liste des bonifications par attributs
      operationId: getBonificationsBy
      tags:
        - Bonification
      parameters:
        - name: code
          in: query
          schema: &a26
            $schema: https://json-schema.org/draft/2020-12/schema
            title: Code
            type: string
            oneOf:
              - &a20
                const: ZNI
                title: Zones non interconnectées au réseau métropolitain continental de
                  transport d'électricité
              - &a21
                const: CPE
                title: Contrat de performance énergétique
              - &a22
                const: CFT
                title: Coup de pouce Chauffage des bâtiments résidentiels collectifs et
                  tertiaires
              - &a23
                const: CRC
                title: Coup de pouce Rénovation performante de bâtiment résidentiel collectif
              - &a24
                const: CRM
                title: Coup de pouce Rénovation performante d'une maison individuelle
              - &a25
                const: CDP
                title: Coup de pouce Chauffage
            $defs:
              ZNI: *a20
              CPE: *a21
              CFT: *a22
              CRC: *a23
              CRM: *a24
              CDP: *a25
              CDC:
                const: CDC
                title: Coup de pouce Covoiturage
            examples:
              - ZNI
              - CPE
              - CFT
              - CRC
              - CRM
              - CDP
        - name: date
          in: query
          description: Date prévue de l'opération
          schema:
            type: string
            format: date
      responses:
        "200":
          description: Bonifications retournées
          content:
            application/json:
              schema:
                type: array
                items: &a33
                  type: object
                  properties:
                    id: &a34
                      title: Bonification
                      type: string
                      oneOf:
                        - const: CDPv50-1
                        - const: CDPv52-1
                        - const: CFTv50-1
                        - const: CPEv40-1
                        - const: CRCv51-1
                        - const: CRMv51-1
                        - const: ZNIv35-1
                      $defs:
                        CDP:
                          type: string
                          pattern: ^CDPv[0-9]{2}[-][0-9]+$
                        CFT:
                          type: string
                          pattern: ^CFTv[0-9]{2}[-][0-9]+$
                        CPE:
                          type: string
                          pattern: ^CPEv[0-9]{2}[-][0-9]+$
                        CRC:
                          type: string
                          pattern: ^CRCv[0-9]{2}[-][0-9]+$
                        CRM:
                          type: string
                          pattern: ^CRMv[0-9]{2}[-][0-9]+$
                        ZNI:
                          type: string
                          pattern: ^ZNIv[0-9]{2}[-][0-9]+$
                    code: *a26
                    nature:
                      $schema: https://json-schema.org/draft/2020-12/schema
                      title: Nature
                      type: string
                      oneOf:
                        - &a27
                          const: ZNI
                          title: Zones non interconnectées au réseau métropolitain continental de
                            transport d'électricité
                        - &a28
                          const: CPE
                          title: Contrat de performance énergétique
                        - &a29
                          const: CFT
                          title: Coup de pouce Chauffage des bâtiments résidentiels collectifs et
                            tertiaires
                        - &a30
                          const: CRC
                          title: Coup de pouce Rénovation performante de bâtiment résidentiel collectif
                        - &a31
                          const: CRM
                          title: Coup de pouce Rénovation performante d'une maison individuelle
                        - &a32
                          const: CDP
                          title: Coup de pouce Chauffage
                      $defs:
                        ZNI: *a27
                        CPE: *a28
                        CFT: *a29
                        CRC: *a30
                        CRM: *a31
                        CDP: *a32
                        CDC:
                          const: CDC
                          title: Coup de pouce Covoiturage
                      examples:
                        - ZNI
                        - CPE
                        - CFT
                        - CRC
                        - CRM
                        - CDP
                    version:
                      type: string
                      pattern: ^[0-9]+[.][0-9]+$
                      examples:
                        - "14.1"
                        - "33.4"
                    nom:
                      type: string
                    dateDebut:
                      type: string
                      format: date
                    dateFin:
                      type:
                        - string
                        - "null"
                      format: date
                  required:
                    - id
                    - code
                    - version
                    - nom
                    - dateDebut
                    - dateFin
                    - nature
  /bonifications/{id}:
    get:
      summary: Recherche une bonification par son identifiant unique
      operationId: getBonificationById
      tags:
        - Bonification
      parameters:
        - name: id
          in: path
          schema:
            type: string
      responses:
        "200":
          description: Bonification retournée
          content:
            application/json:
              schema: *a33
        "404":
          description: Bonification non trouvée
components:
  schemas:
    fiche: *a19
    bonification: *a33
    codeSecteur: *a15
    codeSousSecteur: *a16
    codeFiche: *a17
    codeBonification: *a26
    referenceFiche: *a18
    referenceBonification: *a34
